### ISSUE TITLE
Error : AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by fcabaud** [johnyf/pyan#6]
when à run this command:
python3   pyan.py myprogramm.py   --uses --no-defines --colored --grouped --annotated --dot >myuses.dot

I got this error:

Traceback (most recent call last):
  File "/home/fcabaud/Téléchargements/pyan/pyan.py", line 11, in <module>
    sys.exit(main())
  File "/home/fcabaud/Téléchargements/pyan/pyan/main.py", line 109, in main
    v = CallGraphVisitor(filenames, logger)
  File "/home/fcabaud/Téléchargements/pyan/pyan/analyzer.py", line 77, in __init__
    self.process()
  File "/home/fcabaud/Téléchargements/pyan/pyan/analyzer.py", line 84, in process
    self.process_one(filename)
  File "/home/fcabaud/Téléchargements/pyan/pyan/analyzer.py", line 98, in process_one
    self.visit(ast.parse(content, filename))
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/fcabaud/Téléchargements/pyan/pyan/analyzer.py", line 175, in visit_Module
    self.generic_visit(node)  # visit the **children** of node
  File "/usr/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/fcabaud/Téléchargements/pyan/pyan/analyzer.py", line 375, in visit_ImportFrom
    if self.add_uses_edge(from_node, to_node):
  File "/home/fcabaud/Téléchargements/pyan/pyan/analyzer.py", line 1294, in add_uses_edge
    self.remove_wild(from_node, to_node, to_node.name)
  File "/home/fcabaud/Téléchargements/pyan/pyan/analyzer.py", line 1321, in remove_wild
    if to_node.get_name().find("^^^argument^^^") != -1:
AttributeError: 'NoneType' object has no attribute 'find'

My file is working correctly with python3.6

**Comment by Technologicat** [comment]
Hi,

author of Pyan3 here, this looks like a bug: for some reason, ``to_node`` doesn't have a name.

I can quickly add a check that prevents this particular crash, but it would be nice to know why it is happening, in case it could be a symptom of something more serious. Could you create a minimal example for which this crash occurs, and share it here?

(If there's nothing secret in your original program, alternatively you can share that, too, but any example that causes the crash is sufficient. I don't need to run the program - I just need the ``.py`` file to feed to Pyan, to observe why it's crashing.)

(Note that in general, that the program runs fine doesn't necessarily mean Pyan will be able to analyze it - Python is a large language and Pyan doesn't capture all of it.)

**Comment by fcabaud** [comment]
Well, I can't provide you the original program.
The good new is I found what was wrong.
In the python file, I change code 
```python
from . import LOG_PATH
```
by
```python
LOG_PATH = os.path.abspath(os.path.dirname(__file__) + '../../../../' + os.sep + 'log')
```

this code was in __init__.py


... and it works.

**Comment by Technologicat** [comment]
Ah, that's sufficient, I think I see the problem - it's the relative import.

These are very tricky to handle correctly, to say the least. The problem is that Pyan would need to know the package structure, and how the program being analyzed is actually going to be invoked (!), to guarantee that relative imports resolve the same way as when the program actually runs. The current *"here's a set of files, please analyze them"* approach doesn't provide the required information to do this.

Currently, Pyan only special-cases ``from . import foo`` so that it (mostly) doesn't crash Pyan, and may even occasionally find the right module.

But it seems in any case I need to add some more code to detect ``None`` as the name in ``remove_wild``... thanks for the stack trace!

See e.g.
https://stackoverflow.com/questions/14132789/relative-imports-for-the-billionth-time
https://www.python.org/dev/peps/pep-0328/#id10
